name: Weekly Dependency Check

on:
  schedule:
    - cron: '0 6 * * 1' # every Monday 06:00 UTC
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-outdated
      - name: Check outdated packages
        id: check
        run: |
          pip-outdated --format json > outdated.json || true
          echo "::set-output name=file::$(pwd)/outdated.json"
      - name: Create issue if outdated
        if: steps.check.outputs.file != ''
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'Dependency updates available'
          content-filepath: outdated.json
          labels: 'dependencies'