name: Smoke Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
          # Install CPU torch/torchvision wheel for Ubuntu
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
      - name: Run smoke batch
        run: |
          python tools/run_smoke_batch.py
